# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-05 07:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('soft_delete', models.BooleanField(default=False)),
                ('total_attendance', models.IntegerField()),
                ('obtained_attendance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('soft_delete', models.BooleanField(default=False)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('abbr', models.CharField(db_index=True, max_length=20, unique=True)),
                ('duration', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExamName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('soft_delete', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('soft_delete', models.BooleanField(default=False)),
                ('activity', models.TextField(blank=True, null=True)),
                ('activity_type', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('soft_delete', models.BooleanField(default=False)),
                ('password_request_created_at', models.DateTimeField(auto_now_add=True)),
                ('token', models.TextField()),
                ('token_consumed', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('soft_delete', models.BooleanField(default=False)),
                ('result_type', models.CharField(choices=[('I', 'INTERNAL'), ('E', 'EXTERNAL')], max_length=20)),
                ('batch', models.CharField(max_length=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olt_web.Course')),
                ('exam_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olt_web.ExamName')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResultMain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('soft_delete', models.BooleanField(default=False)),
                ('marks_obtained', models.IntegerField()),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olt_web.Result')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('soft_delete', models.BooleanField(default=False)),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=2)),
                ('dob', models.DateField(blank=True, null=True)),
                ('phone', models.BigIntegerField()),
                ('curr_address', models.TextField()),
                ('perm_address', models.TextField(null=True)),
                ('address_flag', models.BooleanField(default=False)),
                ('photo', models.ImageField(null=True, upload_to='profile-images')),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A-Positive'), ('A-', 'A-Negative'), ('B+', 'B-Positive'), ('B-', 'B-Negative'), ('O+', 'O-Positive'), ('O-', 'O-Negative'), ('AB+', 'AB-Positive'), ('AB-', 'AB-Negative')], max_length=3, null=True)),
                ('roll_no', models.SlugField(unique=True)),
                ('remarks', models.TextField(null=True)),
                ('guardian_name', models.CharField(max_length=50)),
                ('guardian_type', models.CharField(choices=[('F', 'Father'), ('M', 'Mother'), ('G', 'Guradian')], max_length=1)),
                ('guardian_phone', models.CharField(max_length=15)),
                ('batch', models.IntegerField()),
                ('email', models.CharField(max_length=100, unique=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olt_web.Course')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('soft_delete', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=20)),
                ('s_id', models.CharField(max_length=10, unique=True)),
                ('s_type', models.CharField(choices=[('T', 'THEORY'), ('P', 'PRACTICAL')], max_length=10)),
                ('max_marks', models.CharField(max_length=5)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olt_web.Course')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('soft_delete', models.BooleanField(default=False)),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=2)),
                ('dob', models.DateField(blank=True, null=True)),
                ('phone', models.BigIntegerField()),
                ('curr_address', models.TextField()),
                ('perm_address', models.TextField(null=True)),
                ('address_flag', models.BooleanField(default=False)),
                ('photo', models.ImageField(null=True, upload_to='profile-images')),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A-Positive'), ('A-', 'A-Negative'), ('B+', 'B-Positive'), ('B-', 'B-Negative'), ('O+', 'O-Positive'), ('O-', 'O-Negative'), ('AB+', 'AB-Positive'), ('AB-', 'AB-Negative')], max_length=3, null=True)),
                ('e_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('student_permit', models.BooleanField(default=False)),
                ('subject_permit', models.BooleanField(default=False)),
                ('exam_permit', models.BooleanField(default=False)),
                ('result_permit', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='resultmain',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olt_web.Student'),
        ),
        migrations.AddField(
            model_name='result',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olt_web.Subject'),
        ),
        migrations.AddField(
            model_name='passwordreset',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olt_web.Teacher'),
        ),
        migrations.AddField(
            model_name='history',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olt_web.Teacher'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olt_web.Student'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olt_web.Subject'),
        ),
        migrations.AlterUniqueTogether(
            name='resultmain',
            unique_together=set([('student', 'result')]),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set([('student', 'subject')]),
        ),
    ]
